### ISSUE TITLE
Publish/link to presentations

### ISSUE THREAD

**Issue by hamiltont** [dockerparis/docker-pot#7]
I think your team may have given some presentations on docker-pot in the past - any way you could put those slides up online? Or perhaps a video of what docker-pot has added - the descriptions I've found are really promising but it's hard to know what this project adds to docker without seeing it in action.

**Comment by ghigt** [comment]
There are slides from our presentation at the Docker's Hackathon : http://mxs.sbrk.org/public/docker-pot.pdf
If you want to try it, there is also a linux binary : http://mxs.sbrk.org/public/docker-pot.tar.gz

**Comment by hamiltont** [comment]
Great, thank you!

**Comment by hamiltont** [comment]
If you're interested in having a video, I made a quick one: https://asciinema.org/a/17593

Not sure if there are any keyboard bindings, I tried a number of F keys but it just caused screen flickering

**Comment by ghigt** [comment]
Press 'h' for help.

**Comment by aimxhaisse** [comment]
:ok_hand:

**Comment by hamiltont** [comment]
Updated video: https://asciinema.org/a/17886

The process listings are pretty neat

**Comment by ghigt** [comment]
I've created a new project with almost the same code but out of docker, if you're interested: https://github.com/ghigt/dtop

**Comment by mjbright** [comment]
Cool !
Yes, very interested ...
